### ISSUE TITLE
ParseInstallation does not store object ID in key-value store

### ISSUE THREAD

**Issue by jt9897253** [parse-community/Parse-Swift#115]
Assume a struct `MyParseInstallation` conforming to `ParseInstallation`.

If I understand the code correctly, calling `MyParseInstallation.current?.save { (result: Result<AppInstallInfo, ParseError>) in [...] }` intends to persist the ParseInstallation data to the server.

However, calling `MyParseInstallation.current?.fetch(completion: { (result: Result<AppInstallInfo, ParseError>) in [...]}` always returns a failure.

Problem seems to be that `objectId` of `MyParseInstallation` is not persisted to the `ParseKeyValueStore`. Thus, the fetch returns `ParseError(code: ParseSwift.ParseError.Code.unknownError, message: "Cannot fetch an object without id")`

Another effect of not storing `objectId` in the key-value store is that multiple calls to `MyParseInstallation.current?.save` result in multiple ParseInstallation objects being created on the server, all with the same data but different ids.

Tested on both the latest release and the `removeDispatch` branch.

**Comment by cbaker6** [comment]
I'm assuming you are using ParseSwift on Linux/Android? This is very possible, currently looking into the problem...

**Comment by jt9897253** [comment]
> I'm assuming you are using ParseSwift on Linux/Android? 

No, tested on iOS and macCatalyst this time. I'll check if https://github.com/parse-community/Parse-Swift/pull/116 addresses the issue

**Comment by cbaker6** [comment]
> > I'm assuming you are using ParseSwift on Linux/Android?
> 
> No, tested on iOS and macCatalyst this time. I'll check if #116 addresses the issue

Makes sense. When I found what the issue was it showed up across all OSs.

**Comment by funkenstrahlen** [comment]
I also see this issue. Happy to see a fix is already in the works.

**Comment by cbaker6** [comment]
> I also see this issue. Happy to see a fix is already in the works.

Sure, as soon as one of you confirms it works I will merge

**Comment by jt9897253** [comment]
I'm not sure if the behavior improved. Tested the following (branch "current"): save the Installation on app start
Behavior is:
- On first app start, the installation is stored on the server correctly
- On subsequent app starts, getting the `The data couldn’t be read because it is missing.` from #93

**Comment by cbaker6** [comment]
> I'm not sure if the behavior improved. Tested the following (branch "current"): save the Installation on app start
> Behavior is:
> 
> * On first app start, the installation is stored on the server correctly
> * On subsequent app starts, getting the `The data couldn’t be read because it is missing.` from #93

Can you post your actual error and your whole `Installation` struct. Also, can you post what you are calling when you receive this error?

**Comment by jt9897253** [comment]
Install struct:

```
private struct AppInstallInfo: ParseInstallation {
    // required for `ParseObject`
    var objectId: String?
    var createdAt: Date?
    var updatedAt: Date?
    var ACL: ParseACL?
    
    // required for `ParseInstallation`
    var installationId: String?
    var deviceType: String?
    var deviceToken: String?
    var badge: Int?
    var timeZone: String?
    var channels: [String]?
    var appName: String?
    var appIdentifier: String?
    var appVersion: String?
    var parseVersion: String?
    var localeIdentifier: String?
    // custom keys can be added here
}
```

This should be enough to reproduce the issue (parse server running locally in Docker):
```
if let serverURL = URL(string: "http://localhost:1337/parse") {
    ParseSwift.initialize(applicationId: "APPLICATION_ID", clientKey: "CLIENT_KEY", serverURL: serverURL, keyValueStore: myStore)
    
    AppInstallInfo.current?.save { (result: Result<AppInstallInfo, ParseError>) in
        switch result {
        case .success(let updatedAppInstallInfo):
            callback("successfully saved installation on server: \(updatedAppInstallInfo)")
        case .failure(let error):
            callback("failed to save installation on server: \(error)")
        }
    }
} else {
    callback("invalid parse server url")
}
```

Full error:
```
failed to save installation on server: ParseError(code: ParseSwift.ParseError.Code.unknownError, message: "Error decoding parse-server response: Optional(<NSHTTPURLResponse: 0x600002f606c0> { URL: http://localhost:1337/parse/installations } { Status Code: 200, Headers {\n    \"Access-Control-Allow-Headers\" =     (\n        \"X-Parse-Master-Key, X-Parse-REST-API-Key, X-Parse-Javascript-Key, X-Parse-Application-Id, X-Parse-Client-Version, X-Parse-Session-Token, X-Requested-With, X-Parse-Revocable-Session, X-Parse-Request-Id, Content-Type, Pragma, Cache-Control\"\n    );\n    \"Access-Control-Allow-Methods\" =     (\n        \"GET,PUT,POST,DELETE,OPTIONS\"\n    );\n    \"Access-Control-Allow-Origin\" =     (\n        \"*\"\n    );\n    \"Access-Control-Expose-Headers\" =     (\n        \"X-Parse-Job-Status-Id, X-Parse-Push-Status-Id\"\n    );\n    Connection =     (\n        \"keep-alive\"\n    );\n    \"Content-Length\" =     (\n        40\n    );\n    \"Content-Type\" =     (\n        \"application/json; charset=utf-8\"\n    );\n    Date =     (\n        \"Sat, 03 Apr 2021 16:24:52 GMT\"\n    );\n    Etag =     (\n        \"W/\\\"28-73f5/AChhbjMHdlSNQFN7RU2U30\\\"\"\n    );\n    \"Keep-Alive\" =     (\n        \"timeout=5\"\n    );\n    \"X-Powered-By\" =     (\n        Express\n    );\n} }) with error: The data couldn’t be read because it is missing. Format: Optional(\"{\\\"updatedAt\\\":\\\"2021-04-03T16:24:52.550Z\\\"}\")")
```

**Comment by cbaker6** [comment]
Are you still using the same device you were using when it wasn't working? If so, can you try logging out so a new installation is generated

**Comment by jt9897253** [comment]
This was tested on iOS simulator. I just deleted the app, everything from _Installation and the server and the issue is still present on second start.

> If you want to keep your current installation, you can create a query to find your current installation on the server based on the installationId

I think I tried that, but was not allowed (got an error message like "you are not allow to query _Installation").

**Comment by cbaker6** [comment]
I think I see the issue, I'll let you know when I have an update

**Comment by jt9897253** [comment]
> If you want to keep your current installation, you can create a query to find your current installation on the server based on the installationId

Also, as said above, I tried fetching the current installation with 

```
AppInstallInfo.current?.fetch(completion: { (result: Result<AppInstallInfo, ParseError>) in [...]}
```

but this did not work, presumably  as the installation's object id is nil when fetching.

**Comment by cbaker6** [comment]
I just made a commit that should fix the issue

**Comment by cbaker6** [comment]
Be sure to delete your installations from your Parse Dashboard so they are saved properly. You shouldn't need to do anything else.

**Comment by jt9897253** [comment]
In the Installation playground file, running save twice does work. However, saving Installation when the the app has started, still fails when the app is started a second time.

I can reproduce this in the app: when saving the installation two times after one another, I do not get an error. If I then stop the app and run it again, I see the `The data couldn’t be read because it is missing.` error.

Is the in memory store working correctly but when persisting to disk using a custom key-value store (called `myStore` in the above example code) it goes wrong?

**Comment by cbaker6** [comment]
> I can reproduce this in the app: when saving the installation two times after one another, I do not get an error. If I then stop the app and run it again, I see the The data couldn’t be read because it is missing. error.

Can you post how you are saving? It's easier to see what's going on when you post what you are doing and the errors you are getting.

> Is the in memory store working correctly but when persisting to disk using a custom key-value store (called myStore in the above example code) it goes wrong?

I'm not sure what you mean. Are you asking me if your custom key value store is working correctly? You will need to post the code for it for me to determine that

**Comment by jt9897253** [comment]
> Can you post how you are saving? It's easier to see what's going on when you post what you are doing and the "complete" errors you are getting.

Using the following code:

```
if let serverURL = URL(string: "http://localhost:1337/parse") {
    ParseSwift.initialize(applicationId: "APPLICATION_ID", clientKey: "CLIENT_KEY", serverURL: serverURL, keyValueStore: myStore)
    
    AppInstallInfo.current?.save { (result: Result<AppInstallInfo, ParseError>) in
        switch result {
        case .success(_):
            print("successfully saved installation on server")
        case .failure(let error):
            print("failed to save installation on server: \(error)")
        }
    }
    
    AppInstallInfo.current?.save { (result: Result<AppInstallInfo, ParseError>) in
        switch result {
        case .success(_):
            print("successfully saved installation on server")
        case .failure(let error):
            print("failed to save installation on server: \(error)")
        }
    }
} else {
    print("invalid parse server url")
}
```

Results in the following output the first time the app is started:

```
successfully saved installation on server
successfully saved installation on server
``

Results in the following output the second time the app is started:

```
failed to save installation on server: ParseError(code: ParseSwift.ParseError.Code.unknownError, message: "Error decoding parse-server response: Optional(<NSHTTPURLResponse: 0x60000246c020> { URL: http://localhost:1337/parse/installations } { Status Code: 200, Headers {\n    \"Access-Control-Allow-Headers\" =     (\n        \"X-Parse-Master-Key, X-Parse-REST-API-Key, X-Parse-Javascript-Key, X-Parse-Application-Id, X-Parse-Client-Version, X-Parse-Session-Token, X-Requested-With, X-Parse-Revocable-Session, X-Parse-Request-Id, Content-Type, Pragma, Cache-Control\"\n    );\n    \"Access-Control-Allow-Methods\" =     (\n        \"GET,PUT,POST,DELETE,OPTIONS\"\n    );\n    \"Access-Control-Allow-Origin\" =     (\n        \"*\"\n    );\n    \"Access-Control-Expose-Headers\" =     (\n        \"X-Parse-Job-Status-Id, X-Parse-Push-Status-Id\"\n    );\n    Connection =     (\n        \"keep-alive\"\n    );\n    \"Content-Length\" =     (\n        40\n    );\n    \"Content-Type\" =     (\n        \"application/json; charset=utf-8\"\n    );\n    Date =     (\n        \"Sat, 03 Apr 2021 18:20:24 GMT\"\n    );\n    Etag =     (\n        \"W/\\\"28-jHcGQkRKlm9UOcnp+krhVPlfEmE\\\"\"\n    );\n    \"Keep-Alive\" =     (\n        \"timeout=5\"\n    );\n    \"X-Powered-By\" =     (\n        Express\n    );\n} }) with error: The data couldn’t be read because it is missing. Format: Optional(\"{\\\"updatedAt\\\":\\\"2021-04-03T18:20:24.574Z\\\"}\")")
failed to save installation on server: ParseError(code: ParseSwift.ParseError.Code.unknownError, message: "Error decoding parse-server response: Optional(<NSHTTPURLResponse: 0x600002459160> { URL: http://localhost:1337/parse/installations } { Status Code: 200, Headers {\n    \"Access-Control-Allow-Headers\" =     (\n        \"X-Parse-Master-Key, X-Parse-REST-API-Key, X-Parse-Javascript-Key, X-Parse-Application-Id, X-Parse-Client-Version, X-Parse-Session-Token, X-Requested-With, X-Parse-Revocable-Session, X-Parse-Request-Id, Content-Type, Pragma, Cache-Control\"\n    );\n    \"Access-Control-Allow-Methods\" =     (\n        \"GET,PUT,POST,DELETE,OPTIONS\"\n    );\n    \"Access-Control-Allow-Origin\" =     (\n        \"*\"\n    );\n    \"Access-Control-Expose-Headers\" =     (\n        \"X-Parse-Job-Status-Id, X-Parse-Push-Status-Id\"\n    );\n    Connection =     (\n        \"keep-alive\"\n    );\n    \"Content-Length\" =     (\n        40\n    );\n    \"Content-Type\" =     (\n        \"application/json; charset=utf-8\"\n    );\n    Date =     (\n        \"Sat, 03 Apr 2021 18:20:24 GMT\"\n    );\n    Etag =     (\n        \"W/\\\"28-QGBaxYJkLeOr9i2dnKIxCpKMna0\\\"\"\n    );\n    \"Keep-Alive\" =     (\n        \"timeout=5\"\n    );\n    \"X-Powered-By\" =     (\n        Express\n    );\n} }) with error: The data couldn’t be read because it is missing. Format: Optional(\"{\\\"updatedAt\\\":\\\"2021-04-03T18:20:24.576Z\\\"}\")")
```

myStore (of type MyStorage) is simply persisting to user defaults:

```
struct MyStorage: ParseKeyValueStore {
    static private let prefix = "MyStorage"
    static private let encoder = JSONEncoder()
    static private let decoder = JSONDecoder()
    
    mutating func delete(valueFor key: String) throws {
        UserDefaults.standard.removeObject(forKey: key)
        UserDefaults.standard.synchronize()
    }
    
    mutating func deleteAll() throws {
        for (key, _) in UserDefaults.standard.dictionaryRepresentation() {
            if key.prefix(Self.prefix.count) == Self.prefix {
                UserDefaults.standard.removeObject(forKey: key)
            }
        }
        UserDefaults.standard.synchronize()
    }
    
    mutating func get<T>(valueFor key: String) throws -> T? where T: Decodable {
        if let object = UserDefaults.standard.data(forKey: "\(Self.prefix)\(key)") as Data? {
            return try Self.decoder.decode(T.self, from: object)
        }
        
        return nil
    }
    
    mutating func set<T>(_ object: T, for key: String) throws where T: Encodable {
        let encodedObject = try Self.encoder.encode(object)
        UserDefaults.standard.setValue(encodedObject, forKey: "\(Self.prefix)\(key)")
        UserDefaults.standard.synchronize()
    }
}
```

**Comment by cbaker6** [comment]
> Using the following code:

You shouldn't be saving like this, these are two asynchronous calls, there's a high probability they will clash. You need to either switch them to synchronous calls or use below (playgrounds does it because you are suppose to complete each line step-by-step):

```swift
if let serverURL = URL(string: "http://localhost:1337/parse") {
    ParseSwift.initialize(applicationId: "APPLICATION_ID", clientKey: "CLIENT_KEY", serverURL: serverURL, keyValueStore: myStore)
    
    AppInstallInfo.current?.save { (result: Result<AppInstallInfo, ParseError>) in
        switch result {
        case .success(_):
            print("successfully saved installation on server")
        AppInstallInfo.current?.save { (result: Result<AppInstallInfo, ParseError>) in
        switch result {
        case .success(_):
            print("successfully saved installation on server")
        case .failure(let error):
            print("failed to save installation on server: \(error)")
        }
    }
        case .failure(let error):
            print("failed to save installation on server: \(error)")
        }
    }
} else {
    print("invalid parse server url")
}
```

Can you report after you make the fix above. The other issues you mentioned are most likely dependent on how you were saving.

**Comment by jt9897253** [comment]
When performing the asynchronous network calls sequentially the output is as follows.

First run of app:
```
successfully saved installation on server
successfully saved installation on server
```

Second run of app:

```
failed to save installation on server: ParseError(code: ParseSwift.ParseError.Code.unknownError, message: "Error decoding parse-server response: Optional(<NSHTTPURLResponse: 0x600002e68680> { URL: http://localhost:1337/parse/installations } { Status Code: 200, Headers {\n    \"Access-Control-Allow-Headers\" =     (\n        \"X-Parse-Master-Key, X-Parse-REST-API-Key, X-Parse-Javascript-Key, X-Parse-Application-Id, X-Parse-Client-Version, X-Parse-Session-Token, X-Requested-With, X-Parse-Revocable-Session, X-Parse-Request-Id, Content-Type, Pragma, Cache-Control\"\n    );\n    \"Access-Control-Allow-Methods\" =     (\n        \"GET,PUT,POST,DELETE,OPTIONS\"\n    );\n    \"Access-Control-Allow-Origin\" =     (\n        \"*\"\n    );\n    \"Access-Control-Expose-Headers\" =     (\n        \"X-Parse-Job-Status-Id, X-Parse-Push-Status-Id\"\n    );\n    Connection =     (\n        \"keep-alive\"\n    );\n    \"Content-Length\" =     (\n        40\n    );\n    \"Content-Type\" =     (\n        \"application/json; charset=utf-8\"\n    );\n    Date =     (\n        \"Sat, 03 Apr 2021 18:36:52 GMT\"\n    );\n    Etag =     (\n        \"W/\\\"28-IrAxbNLwehO8sf9OQ3bvDlp9cR8\\\"\"\n    );\n    \"Keep-Alive\" =     (\n        \"timeout=5\"\n    );\n    \"X-Powered-By\" =     (\n        Express\n    );\n} }) with error: The data couldn’t be read because it is missing. Format: Optional(\"{\\\"updatedAt\\\":\\\"2021-04-03T18:36:52.394Z\\\"}\")")
```

Error message is shown once as the second save is only performed on success of the first save.

Thus, I do not think this is related to concurrency.

**Comment by cbaker6** [comment]
What happens when you don't use your store. Initializing without it?

**Comment by jt9897253** [comment]
When using 

```swift
if let serverURL = URL(string: "http://localhost:1337/parse") {
    ParseSwift.initialize(applicationId: "APPLICATION_ID", clientKey: "CLIENT_KEY", serverURL: serverURL, keyValueStore: nil)
    
    AppInstallInfo.current?.save { (result: Result<AppInstallInfo, ParseError>) in
        switch result {
        case .success(_):
            print("successfully saved installation on server")
            AppInstallInfo.current?.save { (result: Result<AppInstallInfo, ParseError>) in
                switch result {
                case .success(_):
                    print("successfully saved installation on server")
                case .failure(let error):
                    print("failed to save installation on server: \(error)")
                }
            }
        case .failure(let error):
            print("failed to save installation on server: \(error)")
        }
    }
} else {
    print("invalid parse server url")
}
```

Output for first run of app:

```
successfully saved installation on server
successfully saved installation on server
```

Output for the second run of app:

```
failed to save installation on server: ParseError(code: ParseSwift.ParseError.Code.unknownError, message: "Error decoding parse-server response: Optional(<NSHTTPURLResponse: 0x6000017845a0> { URL: http://localhost:1337/parse/installations } { Status Code: 200, Headers {\n    \"Access-Control-Allow-Headers\" =     (\n        \"X-Parse-Master-Key, X-Parse-REST-API-Key, X-Parse-Javascript-Key, X-Parse-Application-Id, X-Parse-Client-Version, X-Parse-Session-Token, X-Requested-With, X-Parse-Revocable-Session, X-Parse-Request-Id, Content-Type, Pragma, Cache-Control\"\n    );\n    \"Access-Control-Allow-Methods\" =     (\n        \"GET,PUT,POST,DELETE,OPTIONS\"\n    );\n    \"Access-Control-Allow-Origin\" =     (\n        \"*\"\n    );\n    \"Access-Control-Expose-Headers\" =     (\n        \"X-Parse-Job-Status-Id, X-Parse-Push-Status-Id\"\n    );\n    Connection =     (\n        \"keep-alive\"\n    );\n    \"Content-Length\" =     (\n        40\n    );\n    \"Content-Type\" =     (\n        \"application/json; charset=utf-8\"\n    );\n    Date =     (\n        \"Sat, 03 Apr 2021 19:37:23 GMT\"\n    );\n    Etag =     (\n        \"W/\\\"28-hYHodbGPDfWZ3+FzixQzoY+6VGw\\\"\"\n    );\n    \"Keep-Alive\" =     (\n        \"timeout=5\"\n    );\n    \"X-Powered-By\" =     (\n        Express\n    );\n} }) with error: The data couldn’t be read because it is missing. Format: Optional(\"{\\\"updatedAt\\\":\\\"2021-04-03T19:37:23.861Z\\\"}\")")
```

**Comment by cbaker6** [comment]
I'm not able to replicate your problem. I've tried in my own app and in playgrounds:

```swift
//Async
Installation.current?.save {
            print($0)
            Installation.current?.save {
                print($0)
            }
        }
```

```swift
//Sync
try? Installation.current?.save()
        try? Installation.current?.save()
```

Both work fine for me along with playgrounds.

Where are you initializing the Parse SDK? I also mention https://github.com/parse-community/Parse-Swift/issues/93#issuecomment-798917728 about not saving the installation right after initialization. You can see the next comment for the reasons for why it's not needed in most cases https://github.com/parse-community/Parse-Swift/issues/93#issuecomment-798935361. If you really want to initialize there you can try a "dispatch after a second or 2" to see if it helps.

This thread will close once the PR is merged. If you want to try to create a test case in the test files that recreate your use-case and open back the issue, feel free

**Comment by cbaker6** [comment]
@funkenstrahlen can you let us know if this works for you?

**Comment by funkenstrahlen** [comment]
Sure, will try this in the next days and provide feedback.

**Comment by funkenstrahlen** [comment]
I use ParseSwift `1.3.0` now. I can successfully login / logout with authenticated users and anonymous users without seeing any issues. Saving `ParseInstallation.current` works as expected in all cases. My code does not contain any `ParseInstallation.current?.fetch` calls though.

**Comment by funkenstrahlen** [comment]
Thank you for your work and time @cbaker6 ❤️

**Comment by cbaker6** [comment]
> I use ParseSwift `1.3.0` now. I can successfully login / logout with authenticated users and anonymous users without seeing any issues. Saving `ParseInstallation.current` works as expected in all cases. My code does not contain any `ParseInstallation.current?.fetch` calls though.

@funkenstrahlen thanks for your feedback! I made sure to test out Installation.fetch on a server in an attempt to cover corner cases and it seems to work fine now that the 1st objectId` saves properly. Question, did you just upgrade to 1.3.0 and let the auto installation migration (it checks for a locally saved installation without an `objectId`, deletes it, and creates another one), or did you delete your Installations in the dashboard? I ask this to see the ease of upgrading. Besides removing “DispatchQueue” from around `Installation` was there anything else you had to do? If you can give a quick step-by-step, we can link to it when people have questions.

**Comment by funkenstrahlen** [comment]
> Question, did you just upgrade to 1.3.0 and let the auto installation migration (it checks for a locally saved installation without an objectId, deletes it, and creates another one), or did you delete your Installations in the dashboard?

I am currently only testing in the simulator and completely erased the simulator storage after upgrading to 1.3.0.

Therefore all installations I tested are created in a fresh state and I can not comment if the upgrade process works as expected.

**Comment by funkenstrahlen** [comment]
> Besides removing “DispatchQueue” from around Installation was there anything else you had to do?

I did not change anything else than removing the additional dispatch after logout before accessing installation.

As mentioned before I completely erased my existing state in the simulator for a fresh start after that.

**Comment by jt9897253** [comment]
Just tested again with release 1.3.0 and I think `ParseInstallation.current?.fetch` does indeed work correctly now. I do not fully understand what went wrong the last time I checked but assume an error on my side.
@cbaker6 Thank you for all the time you are investing into this project!

**Comment by cbaker6** [comment]
I’m glad it’s working for you!

One note about your custom key/value store, I suggest you use the Parse JSON encoder/decoder as Parse has a custom date strategy the stock encoder doesn’t account for. Besides the date strategy, it’s the stock encoder. This can end up causing unexpected behavior or even worse it won’t decode your objects from the store https://github.com/parse-community/Parse-Swift/blob/be5de49a6c7d7e1e700bba43e279e6e9f54cd2a5/Sources/ParseSwift/Storage/ParseKeyValueStore.swift#L35

let us know if find any other issues!
